# Generated by Django 4.2.20 on 2025-05-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('attack_type', models.CharField(max_length=255)),
                ('status', models.CharField(default='Blocked', max_length=50)),
            ],
        ),
    ]
